apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ include "kogger.name" . }}-crb"
  labels:
{{ include "kogger.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ include "kogger.name" . }}-cr"
subjects:
- kind: ServiceAccount
  name: "{{ include "kogger.name" . }}-sa"
  namespace: {{ .Release.Namespace }}
