apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "kogger.name" . }}-cm"
  labels:
{{ include "kogger.labels" . | indent 4 }}
data:
  EXPOSE_PORT: {{ .Values.port | quote }}
  LOG_LEVEL: {{ .Values.logLevel | quote }}