apiVersion: v1
kind: Service
metadata:
  name: "{{ include "kogger.name" . }}"
  labels:
{{ include "kogger.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.service.port }}
  selector:
{{ include "kogger.matchLabels" . | indent 4 }}