// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: kogger.proto

package koggerrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Kogger_GetLogs_FullMethodName = "/koggerrpc.kogger/GetLogs"
)

// KoggerClient is the client API for Kogger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KoggerClient interface {
	GetLogs(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Pods, error)
}

type koggerClient struct {
	cc grpc.ClientConnInterface
}

func NewKoggerClient(cc grpc.ClientConnInterface) KoggerClient {
	return &koggerClient{cc}
}

func (c *koggerClient) GetLogs(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Pods, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pods)
	err := c.cc.Invoke(ctx, Kogger_GetLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KoggerServer is the server API for Kogger service.
// All implementations must embed UnimplementedKoggerServer
// for forward compatibility.
type KoggerServer interface {
	GetLogs(context.Context, *Void) (*Pods, error)
	mustEmbedUnimplementedKoggerServer()
}

// UnimplementedKoggerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKoggerServer struct{}

func (UnimplementedKoggerServer) GetLogs(context.Context, *Void) (*Pods, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedKoggerServer) mustEmbedUnimplementedKoggerServer() {}
func (UnimplementedKoggerServer) testEmbeddedByValue()                {}

// UnsafeKoggerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KoggerServer will
// result in compilation errors.
type UnsafeKoggerServer interface {
	mustEmbedUnimplementedKoggerServer()
}

func RegisterKoggerServer(s grpc.ServiceRegistrar, srv KoggerServer) {
	// If the following call pancis, it indicates UnimplementedKoggerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Kogger_ServiceDesc, srv)
}

func _Kogger_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KoggerServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kogger_GetLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KoggerServer).GetLogs(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

// Kogger_ServiceDesc is the grpc.ServiceDesc for Kogger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Kogger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "koggerrpc.kogger",
	HandlerType: (*KoggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLogs",
			Handler:    _Kogger_GetLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kogger.proto",
}
